### ISSUE TITLE
interner

### ISSUE THREAD

**Issue by ayazhafiz** [yslide/slide#101]
Currently we have an implicit interner by common subexpression elimination using `Rc`s (#46). The problem is that an implicit approach makes it very difficult to guarantee when common expressions are shared, and using implementations that depend on these facts (like storing pointer values for expressions) becomes error prone.

I propose we add a dedicated intern module to make it more clear what expressions are interned, and provide an interning guarantee that is abstracted behind the module rather than using `Rc::clone` everywhere. The interner can be a shallow wrapper around `Rc`; in fact, I suggest this is the way to go.

An API I am thinking of would look something like

```rust
pub struct Interner<T> {
    interned: Map<T, Rc<T>>,
}

#[derive(Deref)] // maybe you can't derive this, but it should be implemented
pub struct Interned<T> {
    inner: Rc<T>,
}

impl<T> Interner<T> {
    pub fn intern(&mut self, val: T) -> Interned<T>;
}

impl<T> Interned<T> {
    pub fn copy(&self) -> Self;
}
```

The implementor can flush or change this more to fit the use case in slide, but in general I don't think it should be very complicated.

**Comment by luke-bhan** [comment]
can you explain what exactly this is or link something bc I am lost

**Comment by ayazhafiz** [comment]
https://en.wikipedia.org/wiki/String_interning

**Comment by ayazhafiz** [comment]
The idea is you keep a reference to an object rather than that object itself. For some programs like a compiler or slide this is very useful because strings (or expressions) are duplicated often, and the program doesn't run for super long, so it's simple to keep all of them in a giant pile and hand out "tickets" that point to the item that you want to represent rather than allocating a new one.

**Comment by ayazhafiz** [comment]
Okay, #155 is not going to work. But I have a second, maybe better idea:

Use the [lasso](https://docs.rs/lasso/0.3.1/lasso/) crate as an intern store. This doesn't work immediately because lasso only works with strings. But a way to get around this is to store a string "hash" (read: printed value) on each expression. This might seem like overkill when we're only dealing with supplying an interner, but this computed string could be stored and used for hashing purposes as well. I am not 100% this works, but I think it should.

Another idea is just to store a lazy hashmap and R/W expressions to intern there. But I feel like this would be a bigger maintenance cost. I'll try the first idea, and if it fails fall back on this one.

**Comment by ayazhafiz** [comment]
Prioritizing as 1 because this is blocking other work on the frontend

**Comment by ayazhafiz** [comment]
The new idea worked!
